### ISSUE TITLE
Anomaly in number of files in tar files.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/scraper#179]
In scraped data from 10/28, there are many more files containing exactly 864 files, than any other file count.  This seems like a strange anomaly.   Dominant file counts around 200 - 250.  There are very few files with close to 864,  but many files with exactly 864

SELECT count(*) as freq, max_files
FROM `mlab-oti.pipeline_logs.summary`
group by max_files
order by max_files DESC

**Comment by pboothe** [comment]
mlab2s and mlab3s, monitored by eb but otherwise receiving no other traffic.
