### ISSUE TITLE
alerts-staging alerts

### ISSUE THREAD

**Issue by gfr10598** [m-lab/scraper#230]
ClusterIsDown http://status.mlab-staging.measurementlab.net:9093/#/alerts?receiver=slack-alerts-email
RsyncRunningWithoutScraper http://status.mlab-staging.measurementlab.net:9093/#/alerts?receiver=slack-alerts-email

Looks like the staging scraper cluster has been down since Friday late afternoon.  pboothe added note to the channel that it will be ok for the weekend.

**Comment by pboothe** [comment]
A kubernetes upgrade went wrong slowly, taking until Friday evening to go properly pear-shaped, after being started on Thursday evening.

The cluster is not down, but the monitoring and alerting is down, and "If no one gets paged, you don't have uptime" ( https://twitter.com/hashoctothorpe/status/523698074896826368  )

**Comment by pboothe** [comment]
Fixed! Upgrading the kubernetes master seems like a relatively same operation, but upgrading nodes has some risk:
1. Nodes lose their post-creation labels when they are recreated. This means that if the node pool creation command did not include the node labels those nodes need, then they will be missing those labels.
2. Newer versions of the on-node kubernetes core services might require more RAM, moving jobs that used to barely fit into becoming unschedulable.

Both of these bit us in the mlab-staging scraper-cluster upgrade.  https://github.com/m-lab/scraper/pull/232 and https://github.com/m-lab/prometheus-support/pull/172 addressed point 2. Recreating all node-pools with labels this time addressed point 1.
