### ISSUE TITLE
MachineWithoutSidestreamRunning

### ISSUE THREAD

**Issue by measurementlab** [m-lab/scraper#236]
Alertmanager URL: http://status.mlab-oti.measurementlab.net:9093

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab3.lhr05.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab3.lhr05.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab2.ord04.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab2.ord04.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab1.lax03.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab1.lax03.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab1.nuq03.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab1.nuq03.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab3.ams03.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab3.ams03.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab3.sjc01.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab3.sjc01.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab3.lhr02.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab3.lhr02.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab2.sea03.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab2.sea03.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab2.ord01.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab2.ord01.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab3.ywg01.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab3.ywg01.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab3.jnb01.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab3.jnb01.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab1.ams02.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab1.ams02.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab2.ams06.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab2.ams06.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab3.par04.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab3.par04.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22ssh806%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22sidestream%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = MachineWithoutSidestreamRunning
    - instance = mlab1.mpm01.measurement-lab.org:806
    - job = blackbox-targets
    - machine = mlab1.mpm01.measurement-lab.org
    - module = ssh_v4_online
    - service = ssh806
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

TODO: add graph url from annotations.

**Comment by stephen-soltesz** [comment]
Resolved by https://github.com/m-lab/prometheus-support/pull/176
