### ISSUE TITLE
InventoryRsyncdWithoutMachines

### ISSUE THREAD

**Issue by measurementlab** [m-lab/scraper#238]
Alertmanager URL: http://status.mlab-oti.measurementlab.net:9093

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = ooni.mlab
    - instance = ooni.mlab.mlab1.ord02.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab1.ord02.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = ndt.iupui
    - instance = ndt.iupui.mlab2.mil02.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab2.mil02.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = utility.mlab
    - instance = utility.mlab.mlab3.mnl01.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab3.mnl01.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = npad.iupui
    - instance = npad.iupui.mlab3.yyz02.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab3.yyz02.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = ndt.iupui
    - instance = ndt.iupui.mlab1.atl02.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab1.atl02.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = utility.mlab
    - instance = utility.mlab.mlab1.ord02.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab1.ord02.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = utility.mlab
    - instance = utility.mlab.mlab1.iad03.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab1.iad03.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = utility.mlab
    - instance = utility.mlab.mlab3.mad02.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab3.mad02.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = neubot.mlab
    - instance = neubot.mlab.mlab3.mad03.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab3.mad03.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = neubot.mlab
    - instance = neubot.mlab.mlab2.ham01.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab2.ham01.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = ooni.mlab
    - instance = ooni.mlab.mlab3.yvr01.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab3.yvr01.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = ndt.iupui
    - instance = ndt.iupui.mlab3.tnr01.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab3.tnr01.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = ndt.iupui
    - instance = ndt.iupui.mlab1.arn05.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab1.arn05.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = neubot.mlab
    - instance = neubot.mlab.mlab2.mil02.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab2.mil02.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = ndt.iupui
    - instance = ndt.iupui.mlab1.iad03.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab1.iad03.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = neubot.mlab
    - instance = neubot.mlab.mlab1.tpe01.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab1.tpe01.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = ooni.mlab
    - instance = ooni.mlab.mlab1.mia02.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab1.mia02.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = ndt.iupui
    - instance = ndt.iupui.mlab2.den03.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab2.den03.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = npad.iupui
    - instance = npad.iupui.mlab2.tnr01.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab2.tnr01.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = utility.mlab
    - instance = utility.mlab.mlab3.ath03.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab3.ath03.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = ooni.mlab
    - instance = ooni.mlab.mlab1.dub01.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab1.dub01.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = neubot.mlab
    - instance = neubot.mlab.mlab2.den03.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab2.den03.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = utility.mlab
    - instance = utility.mlab.mlab2.mnl01.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab2.mnl01.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = utility.mlab
    - instance = utility.mlab.mlab3.beg01.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab3.beg01.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%29&#43;up%7Bservice%3D%22ssh806%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = InventoryRsyncdWithoutMachines
    - experiment = npad.iupui
    - instance = npad.iupui.mlab1.prg02.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab1.prg02.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = Machine configuration is missing for some rsyncd services.

TODO: add graph url from annotations.

**Comment by stephen-soltesz** [comment]
Resolved by https://github.com/m-lab/prometheus-support/pull/176
