### ISSUE TITLE
scraper rsync timeout not working

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/scraper#241]
A staging alert fired for sjc01-mlab4-npad-iupui-paris-traceroute.

Upon checking the scraper logs, I found that rsync had started a file list operation on 2018-01-21 09:31:01 but as of 2018-01-23 22:55 UTC, the timeout had not killed the rsync job.

```
$ date --utc
Tue Jan 23 22:55:21 UTC 2018

$ kubectl -n scraper logs -c scraper sjc01-mlab4-npad-iupui-paris-traceroute-f6d8c99bf-nqxwz
[2018-01-21 09:31:01,271 INFO scraper.py:224 rsync://npad.iupui.mlab4.sjc01.measurement-lab.org:7999/paris-traceroute] Listing files on server with the command: /usr/bin/timeout -s KILL -t 86400 /usr/bin/rsync -n -vv --out-format %n %M -4 -az --bwlimit=10000 --timeout=300 --contimeout=300 --chmod=u=rwX rsync://npad.iupui.mlab4.sjc01.measurement-lab.org:7999/paris-traceroute scraper_data/npad.iupui.mlab4.sjc01.measurement-lab.org/paris-traceroute
```

**Comment by stephen-soltesz** [comment]
On the scraper slice, we can find a connection to the rsync port on the mlab4.sjc01 machine in a CLOSE_WAIT state, but there is no corresponding connection on the mlab server.

```
tcp     2146      0 10.20.3.16:50892        70.42.244.115:7999      CLOSE_WAIT  
```

**Comment by pboothe** [comment]
ARGH!

**Comment by pboothe** [comment]
This was supposed to be fixed with #225 !

**Comment by pboothe** [comment]
So you can't attach to a running process using GDB inside of a container. That uses ptrace, and ptrace can be used to break outside of the docker container (or, at least, to see outside of the container) and as such is disabled inside containers. That makes this infrequent problem a real challenge to debug...

**Comment by pboothe** [comment]
Happened twice more in the week of April 9-13

**Comment by pboothe** [comment]
Question to investigate: Are these freezes synchronized with the IP whitelist update process?

**Comment by stephen-soltesz** [comment]
@nkinkade can you comment about the ip whitelist scheduling? Does the rsync whitelist restart rsyncd unconditionally? (even if the whitelist does not change?)

**Comment by nkinkade** [comment]
It should only attempt to update rsyncd.conf and restart rsyncd [if there was a change in the whitelist](https://github.com/m-lab/mlabops/blob/master/rsync-whitelist/check_rsync_whitelist.sh#L87).

The script is set to run @daily, which according to the Debian manpage on EB for cron(5) means midnight. (`@daily	Run once a day, "0 0 * * *".`)

**Comment by nkinkade** [comment]
The job appears to take around 20 minutes.

`Date: Mon, 14 May 2018 00:20:30 +0000 (UTC)`

That was the date in the email I got from cron on EB for the job last night.

**Comment by nkinkade** [comment]
The job from last night seems to have taken an hour, which seems more likely. The email date from the job last night:

`Date: Tue, 15 May 2018 01:01:16 +0000 (UTC)`

**Comment by pboothe** [comment]
Got a new error message: "Fork support is only compatible with the epoll1 and poll polling strategies"

**Comment by stephen-soltesz** [comment]
I saw the  "Fork support is only compatible with the epoll1 and poll polling strategies" message also -- but ignored it since it didn't seem to be preventing progress. @pboothe do you know what component it's from? Is this a separate issue from this one?

**Comment by pboothe** [comment]
I do not know, and I don't think it is worth investigating.
