### ISSUE TITLE
RsyncRunningWithoutScraper

### ISSUE THREAD

**Issue by measurementlab** [m-lab/scraper#242]
Alertmanager URL: http://status.mlab-oti.measurementlab.net:9093

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%2C&#43;experiment%29&#43;up%7Bcontainer%3D%22scraper%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = RsyncRunningWithoutScraper
    - experiment = ooni.mlab
    - instance = ooni.mlab.mlab1.sea06.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab1.sea06.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bservice%3D%22rsyncd%22%7D&#43;unless&#43;ON%28machine%2C&#43;experiment%29&#43;up%7Bcontainer%3D%22scraper%22%7D&amp;g0.tab=1
  
    Labels:
  
    - alertname = RsyncRunningWithoutScraper
    - experiment = neubot.mlab
    - instance = neubot.mlab.mlab3.yul02.measurement-lab.org:7999
    - job = blackbox-targets
    - machine = mlab3.yul02.measurement-lab.org
    - module = rsyncd_online
    - service = rsyncd
    - severity = ticket
  
    Annotations:
  
    - hints = 
    - summary = 

TODO: add graph url from annotations.

**Comment by stephen-soltesz** [comment]
Caused by scraper cluster upgrade, and some pods being unscheduled.
