### ISSUE TITLE
ScraperSyncPresentWithoutScraperCollector

### ISSUE THREAD

**Issue by measurementlab** [m-lab/scraper#243]
Alertmanager URL: http://status.mlab-oti.measurementlab.net:9093

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=%28scraper_lastcollectionattempt%7Bcontainer%3D%22scraper-sync%22%7D&#43;unless&#43;ON%28machine%2C&#43;experiment%2C&#43;rsync_module%29&#43;up%7Bcontainer%3D%22scraper%22%7D%29&amp;g0.tab=1
  
    Labels:
  
    - alertname = ScraperSyncPresentWithoutScraperCollector
    - application = scraper-sync
    - cluster = scraper-cluster-scraper-sync-pool
    - container = scraper-sync
    - deployment = scraper-sync
    - experiment = ndt.iupui
    - instance = 10.20.3.3:9090
    - job = kubernetes-pods
    - machine = mlab1.yyc02.measurement-lab.org
    - namespace = default
    - pod_template_hash = 3961228517
    - ready = true
    - rsync_module = ndt
    - service = prometheus-public-service
    - severity = page
    - zone = us-central1-a
  
    Annotations:
  
    - description = 
    - summary = 

TODO: add graph url from annotations.

**Comment by stephen-soltesz** [comment]
Caused by scraper cluster upgrade, and some pods being unscheduled.
