### ISSUE TITLE
ScriptExporterDownOrMissing

### ISSUE THREAD

**Issue by measurementlab** [m-lab/scraper#255]
Alertmanager URL: http://status.mlab-oti.measurementlab.net:9093

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=up%7Bjob%3D%22script-exporter%22%7D&#43;%3D%3D&#43;0&#43;or&#43;absent%28up%7Bjob%3D%22script-exporter%22%7D%29&amp;g0.tab=1
  
    Labels:
  
    - alertname = ScriptExporterDownOrMissing
    - instance = script-exporter.mlab-oti.measurementlab.net:9100
    - job = script-exporter
    - severity = ticket
  
    Annotations:
  
    - hints = The script_exporter service runs in a Docker container on a GCE VM named &#39;script-exporter&#39; in each M-Lab GCP project. For deployment details and troubleshooting, you can usually figure out the issue by looking through the Travis-CI build logs: https://travis-ci.org/m-lab/prometheus-script-exporter. You can also look for hints in the dashboard for the GCE instance, or by SSHing to the instance itself.
    - summary = The script_exporter service is down on script-exporter.mlab-oti.measurementlab.net:9100.

TODO: add graph url from annotations.

**Comment by stephen-soltesz** [comment]
@gfr10598 reported that GCE recommended upgrading the instance RAM.

This is the second time the script-exporter has had high-memory usage.

I've manually restarted the docker instances using the commands below from `deploy_script_exporter.sh` -- these should start automatically after GCE instance reboot.

```
script-exporter soltesz # docker run --cap-add NET_ADMIN -p 9172:9172 -d m-lab/prometheus-script-exporter
6b15c3909d1b5100e65f5aa53ba955a46cfb0cec09dd6c1ecce236f4ef58f1b1

script-exporter soltesz # docker run --detach --publish 9100:9100 --volume /proc:/host/proc --volume /sys:/host/sys
 prom/node-exporter --path.procfs /host/proc --path.sysfs /host/sys --no-collector.arp --no-collector.bcache --no-c
ollector.conntrack --no-collector.edac --no-collector.entropy --no-collector.filefd --no-collector.hwmon --no-colle
ctor.infiniband --no-collector.ipvs --no-collector.mdadm --no-collector.netstat --no-collector.sockstat --no-collec
tor.time --no-collector.timex --no-collector.uname --no-collector.vmstat --no-collector.wifi --no-collector.xfs --n
o-collector.zfs 
f85cc19062b131087f4cf9325387ca40b0c6143ef969f1813dadd57b2c8284b8
```

**Comment by stephen-soltesz** [comment]
Link to ops dashboard from alertname="ScriptExporterMissingMetrics" is broken. Needs to be updated for .json file.

**Comment by stephen-soltesz** [comment]
New issues to track resolution:
https://github.com/m-lab/ops-tracker/issues/322
https://github.com/m-lab/prometheus-support/issues/194
