### ISSUE TITLE
ScriptExporterMissingMetrics

### ISSUE THREAD

**Issue by measurementlab** [m-lab/scraper#256]
Alertmanager URL: http://status.mlab-oti.measurementlab.net:9093

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=absent%28script_success%7Bservice%3D%22ndt_e2e%22%7D%29&#43;or&#43;absent%28script_success%7Bservice%3D%22ndt_queue%22%7D%29&amp;g0.tab=1
  
    Labels:
  
    - alertname = ScriptExporterMissingMetrics
    - service = ndt_queue
    - severity = page
  
    Annotations:
  
    - dashboard = http://status.mlab-oti.measurementlab.net:3000/dashboard/db/ops-dashboard
    - gcsbucket = https://console.cloud.google.com/storage/browser/operator-mlab-oti/prometheus/script-targets
    - hints = If the script_exporter service is running, then there may be a target configuration error. Check the target definitions in GCS and the target status in Prometheus.
    - prometheus_targets = http://status.mlab-oti.measurementlab.net:9090/targets
    - summary = Expected script_exporter metrics are missing from Prometheus!

  * firing http://status.mlab-oti.measurementlab.net:9090/graph?g0.expr=absent%28script_success%7Bservice%3D%22ndt_e2e%22%7D%29&#43;or&#43;absent%28script_success%7Bservice%3D%22ndt_queue%22%7D%29&amp;g0.tab=1
  
    Labels:
  
    - alertname = ScriptExporterMissingMetrics
    - service = ndt_e2e
    - severity = page
  
    Annotations:
  
    - dashboard = http://status.mlab-oti.measurementlab.net:3000/dashboard/db/ops-dashboard
    - gcsbucket = https://console.cloud.google.com/storage/browser/operator-mlab-oti/prometheus/script-targets
    - hints = If the script_exporter service is running, then there may be a target configuration error. Check the target definitions in GCS and the target status in Prometheus.
    - prometheus_targets = http://status.mlab-oti.measurementlab.net:9090/targets
    - summary = Expected script_exporter metrics are missing from Prometheus!

TODO: add graph url from annotations.

**Comment by stephen-soltesz** [comment]
See: https://github.com/m-lab/scraper/issues/255
