### ISSUE TITLE
Tag new version of scraper

### ISSUE THREAD

**Issue by nkinkade** [m-lab/scraper#258]
PR #257 updated the operator and travis submodules. The update to the operator submodule brings in two new pods which need scraping: FLN01 and HND02. FLN01 is up and running, but I haven't enabled Nagios monitoring so that mlab-ns will not serve it up until scraper is tagged and scraping this site. HND02 is not up yet, but we might as well prepare for it now.

Could someone please tag me in this issue when scraper is tagged and deployed to production as a flag for me to enable Nagios monitoring for FLN01?

**Comment by pboothe** [comment]
I'm on this.  I'm on call this week and I wrote scraper, so this is really my problem. I'll send out a PR shortly - I'd like to get a better version of the git-hooks repo checked in as well.

**Comment by pboothe** [comment]
Done: https://github.com/m-lab/scraper/releases/tag/1.1.5
