### ISSUE TITLE
ScriptExporterDownOrMissing

### ISSUE THREAD

**Issue by measurementlab** [m-lab/scraper#279]
Alertmanager URL: https://alertmanager.mlab-oti.measurementlab.net

  * firing https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=up%7Bjob%3D%22script-exporter%22%7D&#43;%3D%3D&#43;0&#43;or&#43;absent%28up%7Bjob%3D%22script-exporter%22%7D%29&amp;g0.tab=1
  
    Labels:
  
    - alertname = ScriptExporterDownOrMissing
    - instance = script-exporter.mlab-oti.measurementlab.net:9100
    - job = script-exporter
    - severity = ticket
  
    Annotations:
  
    - hints = The script_exporter service runs in a Docker container on a GCE VM named &#39;script-exporter&#39; in each M-Lab GCP project. For deployment details and troubleshooting, you can usually figure out the issue by looking through the Travis-CI build logs: https://travis-ci.org/m-lab/prometheus-script-exporter. You can also look for hints in the dashboard for the GCE instance, or by SSHing to the instance itself.
    - summary = The script_exporter service is down on script-exporter.mlab-oti.measurementlab.net:9100.

  * firing https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=up%7Bjob%3D%22script-exporter%22%7D&#43;%3D%3D&#43;0&#43;or&#43;absent%28up%7Bjob%3D%22script-exporter%22%7D%29&amp;g0.tab=1
  
    Labels:
  
    - alertname = ScriptExporterDownOrMissing
    - instance = script-exporter.mlab-oti.measurementlab.net:9172
    - job = script-exporter
    - severity = ticket
  
    Annotations:
  
    - hints = The script_exporter service runs in a Docker container on a GCE VM named &#39;script-exporter&#39; in each M-Lab GCP project. For deployment details and troubleshooting, you can usually figure out the issue by looking through the Travis-CI build logs: https://travis-ci.org/m-lab/prometheus-script-exporter. You can also look for hints in the dashboard for the GCE instance, or by SSHing to the instance itself.
    - summary = The script_exporter service is down on script-exporter.mlab-oti.measurementlab.net:9172.

TODO: add graph url from annotations.

**Comment by pboothe** [comment]
A side effect of a funny deployment. Fixed by OTI.
