### ISSUE TITLE
NagiosExporterMissing

### ISSUE THREAD

**Issue by measurementlab** [m-lab/scraper#282]
Alertmanager URL: https://alertmanager.mlab-oti.measurementlab.net

  * firing https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=absent%28up%7Bjob%3D%22nagios-oam-exporter%22%7D%29&#43;or&#43;absent%28up%7Bjob%3D%22nagios-exporter%22%7D%29&amp;g0.tab=1
  
    Labels:
  
    - alertname = NagiosExporterMissing
    - job = nagios-exporter
    - severity = ticket
  
    Annotations:
  
    - hints = The Nagios exporter instance should run in a Linode VM.
    - summary = The Nagios exporter instance is not being monitored.

TODO: add graph url from annotations.

**Comment by pboothe** [comment]
A side effect of a funny deployment. Fixed by OTI.

Although soon this alert will be deleted because we will no longer depend on Nagios!
