### ISSUE TITLE
LameDuckMetricMissingForNode

### ISSUE THREAD

**Issue by measurementlab** [m-lab/scraper#298]
Alertmanager URL: https://mlab:YOztKFSKnRMz2GN1qFPueAku9WhmDYV2@alertmanager.mlab-oti.measurementlab.net

  * firing https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=count%28up%7Bservice%3D%22nodeexporter%22%7D&#43;%3D%3D&#43;1&#43;unless&#43;ON%28machine%29&#43;lame_duck_node%29&#43;%3E&#43;0&amp;g0.tab=1
  
    Labels:
  
    - alertname = LameDuckMetricMissingForNode
    - severity = ticket
  
    Annotations:
  
    - hints = Check /var/spool/node_exporter/ on the node to see if the file lame_duck.prom is missing. If it is, use the mlabops Ansible lame-duck.yaml playbook to restore it.
    - summary = Some number of nodes are missing lame-duck status metrics.

TODO: add graph url from annotations.

**Comment by stephen-soltesz** [comment]
Same root cause as https://github.com/m-lab/scraper/issues/297 except this alert cannot be silenced yet.

Opened issue https://github.com/m-lab/prometheus-support/issues/227 to resolve the issue with this alert.

Leaving issue open so a new one is not created.
