### ISSUE TITLE
NodeExporterOnEbDownOrMissing

### ISSUE THREAD

**Issue by measurementlab** [m-lab/scraper#312]
Alertmanager URL: https://mlab:YOztKFSKnRMz2GN1qFPueAku9WhmDYV2@alertmanager.mlab-oti.measurementlab.net

  * firing https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=up%7Bjob%3D%22eb-node-exporter%22%7D&#43;%3D%3D&#43;0&#43;or&#43;absent%28up%7Bjob%3D%22eb-node-exporter%22%7D%29&amp;g0.tab=1
  
    Labels:
  
    - alertname = NodeExporterOnEbDownOrMissing
    - instance = eb.measurementlab.net:9100
    - job = eb-node-exporter
    - severity = ticket
  
    Annotations:
  
    - hints = Login to EB to see if it is in fact crashed. If so, look through the logs.
    - summary = The node_exporter instance running on eb.measurementlab.net is down.

TODO: add graph url from annotations.

**Comment by pboothe** [comment]
It looks like a service on EB did not restart when EB did.  This is an issue to be handled by OTI.

**Comment by nkinkade** [comment]
I had apparently failed to enable the systemd service unit for node_exporter. I resolved this and started the serviced. This alert should clear momentarily, and should not happen again should EB get rebooted.

**Comment by nkinkade** [comment]
Issue, and alert, resolved. Closing issue.
