### ISSUE TITLE
deployments should be deleted if missing from generated configs

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/scraper#65]
When removing a site from sites.py and redeploying scraper, the old deployments will still be running and must be deleted manually. Is it possible to remove the old deployments without disrupting everything else?

**Comment by pboothe** [comment]
Not with a single line of  a `kubectl` command, but this is a good idea.

**Comment by pboothe** [comment]
Resolving this will also resolve #84

**Comment by pboothe** [comment]
#79 was the first attempt.

**Comment by pboothe** [comment]
#86 should resolve this.

**Comment by pboothe** [comment]
Resolved. May have some lingering issues related to old deployments, but all new deployments should get auto-deleted when the site is turned down.
