### ISSUE TITLE
Scrapers do not have access to datastore suddenly

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/scraper#70]
Around 6:25 AM ET 2017/06/17 - all scraper instances crashed.

![scraper-down](https://user-images.githubusercontent.com/1085316/27289052-9ecb4488-54d6-11e7-9c98-dce267e4702a.png)

Logs include:
```
google.cloud.exceptions.PreconditionFailed: 412 The Cloud Datastore API is not enabled for the project mlab-staging
```

And,

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
```

**Comment by stephen-soltesz** [comment]
The cloud console describes scraper node scopes as: "This instance has full API access to all Google Cloud services"

And, querying gcloud directly:
```
gcloud beta compute instances describe ... 
```

Reports all the expected scopes.

**Comment by pboothe** [comment]
So, this is surprising, and makes me think something in cloud changed.  Argh. I will investigate.

**Comment by pboothe** [comment]
I have relaunched staging at ~11am.  If I am right that this is happening because of permissions expiring after 12 hours, then everything should go to hell around midnight tonight.

**Comment by pboothe** [comment]
Update: 2:45 am, because I redeployed to staging at 2:40pm to verify that autodeploy still worked.

**Comment by pboothe** [comment]
I am resolving this as a cloud issue and not a scraper issue. If it reoccurs, then I will add code to make it so that cloud datastore dying doesn't break our stuff.

**Comment by pboothe** [comment]
This issue happened once and never reoccurred.  I am closing this issue and making a feature request: #94
